language: objective-c
matrix:
  include:
    - osx_image: xcode7.3
env:
  global:
    - LC_CTYPE=en_US.UTF-8
git:
  submodules: false

before_install:
  - git submodule update --init --recursive
  - brew update
  - brew install carthage

script:
  - pod repo update
  - pod spec lint SwiftFlux.podspec --allow-warnings
  - set -o pipefail
  - carthage build --no-skip-current --platform Mac,iOS
  - rake test:ios
  - rake test:osx

notifications:
  email: false
